---

on:
  push:

jobs:
  test:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - run: |
          curl -LO https://github.com/lucasg/Dependencies/releases/download/v1.11.1/Dependencies_x64_Release.zip
          unzip Dependencies_x64_Release.zip
      - run: |
          curl -LO https://github.com/brechtsanders/winlibs_mingw/releases/download/13.2.0posix-17.0.6-11.0.1-msvcrt-r3/winlibs-x86_64-posix-seh-gcc-13.2.0-llvm-17.0.6-mingw-w64msvcrt-11.0.1-r3.7z
          7z x -y winlibs-x86_64-posix-seh-gcc-13.2.0-llvm-17.0.6-mingw-w64msvcrt-11.0.1-r3.7z
      - run: ./Dependencies.exe -modules mingw64/bin/clang.exe
      - run: ./Dependencies.exe -chain mingw64/bin/clang.exe
